EXEC USP_PRI_MODULO_G '5','SISTEMA DE FACTURACION','','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1','INICIO','5','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.1','Ayuda','5.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.1.1','Manuales','5.1.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.1.2','Tutoriales','5.1.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.1.3','Procedimientos','5.1.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.1.4','Preguntas Frecuentes','5.1.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.1.5','Consulta Tecnica','5.1.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.1.6','Contactenos','5.1.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.2','Herramientas','5.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.2.1','Configuracion','5.1.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.2.2','ReImprimir','5.1.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.2.3','Exportar','5.1.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.2.4','Importar','5.1.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.3','Adminsitrador','5.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.3.1','Cambio de Caja','5.1.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.3.2','Cambio de Turno','5.1.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.1.3.3','Cambiar de Usuario','5.1.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2','VENTAS','5','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.1','Documentos de Ventas','5.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.1.1','Limpiar Ventas','5.2.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.1.2','Nueva Venta','5.2.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.1.3','Nueva Comanda','5.2.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.1.4','Venta Simple','5.2.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.1.5','Venta Completa','5.2.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.1.6','Rapida Con Papel','5.2.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.1.7','Rapida Con Agua','5.2.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.1.8','Rapida Con Gaseosa','5.2.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.1.9','Registro De Ventas','5.2.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.1.10','Registro De Ventas de Exportacion','5.2.1.','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.1.11','Cambio De Precios','5.2.1.','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.1.12','Serafin','5.2.1.','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.2','Documentos Contables','5.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.2.1','Notas De Credito','5.2.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.2.2','Notas De Debito','5.2.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.2.3','Retencion','5.2.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.2.4','Percepcion','5.2.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.2.5','Guias De Remision','5.2.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.2.6','Letras','5.2.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.3','Movimientos de Caja','5.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.3.1','Recibo de Ingreso','5.2.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.3.2','Recibo de Egreso','5.2.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.3.3','Venta de Dolares','5.2.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.3.4','Envio de efectivo','5.2.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.4','Clientes','5.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.2.4.1','Clientes','5.2.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3','COMPRAS','5','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.1','Documentos','5.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.1.1','Facturas Recibidas','5.3.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.2','Movimientos De Caja','5.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.2.1','Recibo De Ingreso','5.3.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.2.2','Recibo De Egreso','5.3.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.2.3','Compra De Dolares','5.3.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.2.4','Rececpcion De Efectivo','5.3.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.3','Documentos Contables','5.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.3.1','Notas De Credito','5.3.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.3.2','Notas De Debito','5.3.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.3.3','Retencion','5.3.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.3.4','Percepcion','5.3.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.4','Proveedor','5.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.3.4.1','Proveedores','5.3.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4','ALMACEN','5','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.1','Configuracion','5.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.1.1','Almacenes','5.4.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.1.2','Productos Servicios','5.4.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.2','Consultas','5.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.2.1','Entradas y Salidas','5.4.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.2.2','Trazabilidad','5.4.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.3','Movimientos','5.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.3.1','Registro De Entradas','5.4.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.3.2','Registro De Salidas','5.4.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.3.3','Convertir Producto','5.4.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.4','Herramientas','5.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.4.1','Inventarios','5.4.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.4.2','Volcado De Stock','5.4.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.4.3','Regeneracion De Caja','5.4.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.4.4','Tanques','5.4.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.4.5','Medicion De Varillaje','5.4.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.4.4.6','Medicion De Contometros','5.4.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.5','ADMINISTRACION','5','MIGRACION';
EXEC USP_PRI_MODULO_G '5.5.1','Cobros','5.5','MIGRACION';
EXEC USP_PRI_MODULO_G '5.5.1.1','Cuentas Por Cobrar','5.5.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.5.1.2','Estado De Cliente','5.5.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.5.2','Pagos','5.5','MIGRACION';
EXEC USP_PRI_MODULO_G '5.5.2.1','Cuentas Por Pagar','5.5.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.5.2.2','Estado Del Proveedor','5.5.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.5.3','Bancos','5.5','MIGRACION';
EXEC USP_PRI_MODULO_G '5.5.3.1','Movimientos Bancarios','5.5.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.5.3.2','Estados De Cuenta','5.5.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.5.4','Formalizacion','5.5','MIGRACION';
EXEC USP_PRI_MODULO_G '5.5.4.1','Documentos A Formalizar','5.5.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6','REPORTES','5','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.1','Ventas','5.6','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.1.1','Reporte De Ventas','5.6.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.1.2','Formas de Cobro','5.6.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.1.3','Estado De Cuenta','5.6.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.1.4','Ventas Por Placa','5.6.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.1.5','Serafin','5.6.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.1.6','Licitaciones','5.6.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.1.7','Resumen Ventas Cajero','5.6.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.1.8','Insumos Quimicos','5.6.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.1.9','Cuentas Por Cobrar','5.6.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.2','Compras','5.6','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.2.1','Reporte De Compras','5.6.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.2.2','Formas De Pago','5.6.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.2.3','Cuentas Por Pagar','5.6.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.3','Almacen','5.6','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.3.1','Reporte De Entradas','5.6.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.3.2','Reporte De Salidas','5.6.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.3.3','Stock','5.6.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.3.4','Kardex','5.6.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.4','Administracion','5.6','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.4.1','Cuentas Por Pagar','5.6.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.4.2','Cuentas Por Cobrar','5.6.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.4.3','Movimientos de Caja','5.6.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.4.4','Resumen De Caja','5.6.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.4.5','Movimientos Bancarios','5.6.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.5','Contometros y Varillas','5.6','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.5.1','RIC','5.6.5','MIGRACION';
EXEC USP_PRI_MODULO_G '5.6.5.2','Contometros VS Documentos','5.6.5','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7','ASISTENCIA TECNICA','5','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.1','Videos','5.7','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.1.1','Esencial','5.7.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.1.2','Novedades','5.7.1','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.2','Primeros Pasos','5.7','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.2.1','Ver Documento','5.7.2','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.3','Palerp.com','5.7','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.3.1','Zona Empresarial','5.7.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.3.2','iFacturacion.pe','5.7.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.3.3','Contacto','5.7.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.3.4','Comprobar Version','5.7.3','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.4','Servicio Para Usuarios Registrados','5.7','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.4.1','Registro','5.7.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.4.2','Centro de Soporte En Linea','5.7.4','MIGRACION';
EXEC USP_PRI_MODULO_G '5.7.4.3','Datos Usuario','5.7.4','MIGRACION';
--Agregamos un parametro del tipo de negocio en la tabla 099
IF NOT	EXISTS (SELECT vc.* FROM dbo.VIS_CONFIGURACION vc WHERE vc.Cod_Configuracion='TIPO_NEGOCIO')
BEGIN
	DECLARE @Fila int = ISNULL((SELECT MAX(vc.Nro) FROM dbo.VIS_CONFIGURACION vc),0)+1
	EXEC dbo.USP_PAR_FILA_G @Cod_Tabla = '099', @Cod_Columna = '001', @Cod_Fila = @Fila, @Cadena = N'TIPO_NEGOCIO', @Numero = NULL, @Entero = NULL, @FechaHora = NULL, @Boleano = NULL, @Flag_Creacion = 1, @Cod_Usuario = 'MIGRACION';
	EXEC dbo.USP_PAR_FILA_G @Cod_Tabla = '099', @Cod_Columna = '002', @Cod_Fila = @Fila, @Cadena = N'', @Numero = NULL, @Entero = NULL, @FechaHora = NULL, @Boleano = NULL, @Flag_Creacion = 1, @Cod_Usuario = 'MIGRACION';
	EXEC dbo.USP_PAR_FILA_G @Cod_Tabla = '099', @Cod_Columna = '003', @Cod_Fila = @Fila, @Cadena = NULL, @Numero = NULL, @Entero = NULL, @FechaHora = NULL, @Boleano = 1, @Flag_Creacion = 1, @Cod_Usuario = 'MIGRACION';
END